#ifndef __COM_CONFIG_H__
#define __COM_CONFIG_H__
#include "com_printf.h"
#include "com_statistic.h"
// #include "com_jdy_at.h"
// #include "com_buzzer.h"
// #include "com_dht11.h"
// #include "com_oled.h"
// #include "com_key.h"
// #include "com_buzzer.h"
// #include "com_tb6612.h"
// #include "com_sr04.h"
// #include "com_steer.h"
// #include "com_mpu6050.h"
// #include "com_oled.h"
// #include "com_mq2.h"
#include "com_uart.h"
#include "com_time.h"
#include "com_os.h"
#endif